language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0-preview2-1-003177

branches:
  only:
  - master

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.4

script:
  - chmod +x build.sh 
  - ./build.sh
